services:
  minerva:
    image: localhost/minerva
    build: .
    ports:
      - "9999:9999"
  
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=minerva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "5432:5432"